name: Ok To Test

on:
  issue_comment:
    types: [created]

jobs:
  ok-to-test:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
    - name: SlashCommandDispatch
      uses: peter-evans/slash-command-dispatch@v1
      with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }} # PAT or OAuth token will also work
        issue-type: pull-request
        commands: ok-to-test
        named-args: true
        permission: read
